### ISSUE TITLE
Feature: User can create an account

### ISSUE THREAD

**Issue by David-Gonzalez11** [David-Gonzalez11/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account with a username and a password

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to click a create account button to be taken to the create account form 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] create the schema with proper tables 
 -[ ] Get the information from the user (username/password)
- [ ] Query the database to insert the values the user inputs

### ☁️ Server Tasks

- [x] Update `server/index.js` to  handle the any errors or invalid inputs from the user
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [ ]  use a post request to /api/auth/sign-up to create new account 
- [x]  hash the password and catch any errors 

### ⚡ Client Tasks

- [x] Create a component to render a sign up page 
- [x]  component should have button for signing up 

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
